{
 "title": "Strimzi Kafka Exporter",
 "description": "Kafka topics and consumer groups",
 "tags": [
  "Strimzi",
  "Kafka",
  "Kafka Exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "kublr_space", "label": "Space", "query": "label_values(kublr_space)" },
   {
    "name": "kublr_cluster",
    "label": "Kublr Cluster",
    "query": "query_result(kafka_server_replicamanager_leadercount{kublr_space=\"$kublr_space\"})"
   },
   {
    "name": "kf",
    "query": "query_result(absent({__non_existing_label_for_substitution__=\"kublr_space=\\\"${kublr_space}\\\",kublr_cluster=\\\"${kublr_cluster}\\\"\"}))"
   },
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "query_result(kafka_exporter_build_info{$kf})"
   },
   {
    "name": "strimzi_cluster_name",
    "label": "Cluster Name",
    "query": "query_result(kafka_exporter_build_info{$kf,namespace=\"$kubernetes_namespace\"})"
   },
   {
    "name": "consumergroup",
    "label": "Consumer Group",
    "query": "label_values(kafka_consumergroup_current_offset{$kf,namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"}, consumergroup)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{$kf,namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Topics",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_topic_partitions{$kf,topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{$kf,topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas{$kf,topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "In Sync Replicas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_in_sync_replica{$kf,topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{$kf,topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions at minimum ISR",
   "type": "singlestat",
   "description": "Number of partitions which are at their minimum in sync replica count (| ISR | == | min.insync.replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_atminisr{$kf,topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions under minimum ISR",
   "type": "singlestat",
   "description": "Number of partitions which are under their minimum in sync replica count (| ISR | < | min.insync.replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{$kf,topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions not on preferred node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_topic_partition_leader_is_preferred{$kf,topic=~\"$topic\"}<1)"
    }
   ]
  },
  {
   "title": "Messages in per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{$kf,topic=~\"$topic\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages consumed per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{$kf,consumergroup=~\"$consumergroup\",topic=~\"$topic\"}[1m])/60) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{$kf,consumergroup=~\"$consumergroup\",topic=~\"$topic\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Consumer Group Offsets",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{$kf,consumergroup=~\"$consumergroup\",topic=~\"$topic\"}) by (consumergroup,partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{$kf,consumergroup=~\"$consumergroup\",topic=~\"$topic\"}) by (consumergroup,partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number of Partitions",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{$kf,topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Latest Offsets",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{$kf,topic=~\"$topic\"}) by (partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Oldest Offsets",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_oldest_offset{$kf,topic=~\"$topic\"}) by (partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}